# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Install FSharpLint globally
      run: dotnet tool install -g dotnet-fsharplint
    - name: Install Fantomas globally
      run: dotnet tool install -g fantomas-tool
    - name: Run FSharpLint
      run: dotnet fsharplint lint --recursive .
    - name: Check formatting with Fantomas
      run: find . -type f -name "*.fs" -not -path "*obj*" | xargs fantomas --check -v d
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
